### ISSUE TITLE
Building and server running

### ISSUE THREAD

**Issue by Raj9039852537** [evanw/rapt#11]
Sir,
 Following error occurred while  trying to install & building server on local machine using python 3.4 & ruby 2.1.5 on window 7 machine, please tell me what's wrong or what should I do.
	With regards
D:\rapt-master>python build.py release
  File "build.py", line 8
    print 'mode: release (run once and compress)'
                                                ^
SyntaxError: invalid syntax

D:\downtemp\Card\2g card\ucdownload feb 15\rapt-master>bundle install
'bundle' is not recognized as an internal or external command,
operable program or batch file.

rake aborted!
uninitialized constant Bundler
D:/rapt-master/rails/config/boot.rb:9:in `rescue in <top (re
quired)>'
D:/rapt-master/rails/config/boot.rb:5:in `<top (required)>'
D:/rapt-master/rails/config/application.rb:1:in `<top (requi
red)>'
D:/rapt-master/rails/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)

D:\downtemp\Card\2g card\ucdownload feb 15\rapt-master\rails>ruby script/rails server
D:/downtemp/Card/2g card/ucdownload feb 15/rapt-master/rails/config/boot.rb:9:in `rescue in <top (re
quired)>': uninitialized constant Bundler (NameError)
        from D:/downtemp/Card/2g card/ucdownload feb 15/rapt-master/rails/config/boot.rb:5:in `<top
(required)>'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby21/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from script/rails:5:in `<main>'

**Comment by evanw** [comment]
You'll need Python 2.7 instead of Python 3.4. Python 3 broke a bunch of stuff.

You also need Bundler, which is usually installed using `gem install bundler`. I don't have Ruby set up on my Windows machine though, so I haven't tried building the server on Windows.

It appears the code has bit-rotted quite a bit since we made this in 2011, so it's probably a bit of a project to get it running again. You'll also need a version of ruby <2.0, for example, since 2.0 introduced some breaking changes (http://dev.af83.com/2013/10/21/ruby-2-0-respond-to.html, for example). I'm tracking that in issue #12.

**Comment by Raj9039852537** [comment]
after following above steps following error occured with ruby 1.9.1

after error i traced the path & there is a file named sqlite3_native.so in the directory.

D:\My-Web-Sites\rapt-master\rails>rake db:setup --trace
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake/alt_system.rb:32: Use RbConfig instead of obsolete and deprecated Config.
(in D:/My-Web-Sites/rapt-master/rails)
rake aborted!
cannot load such file -- sqlite3/sqlite3_native
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `block in require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `block in load_dependency'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:596:in `new_constants_in'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:225:in `load_dependency'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/activesupport-3.0.6/lib/active_support/dependencies.rb:239:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sqlite3-1.3.3-x86-mingw32/lib/sqlite3.rb:6:in `rescue in <top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/sqlite3-1.3.3-x86-mingw32/lib/sqlite3.rb:2:in `<top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.8.2/lib/bundler/runtime.rb:76:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.8.2/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.8.2/lib/bundler/runtime.rb:72:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.8.2/lib/bundler/runtime.rb:72:in `block in require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.8.2/lib/bundler/runtime.rb:61:in `each'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.8.2/lib/bundler/runtime.rb:61:in `require'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/bundler-1.8.2/lib/bundler.rb:134:in `require'
D:/My-Web-Sites/rapt-master/rails/config/application.rb:7:in `<top (required)>'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
C:/Ruby193/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
D:/My-Web-Sites/rapt-master/rails/Rakefile:4:in `<top (required)>'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2383:in `load'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2383:in `raw_load_rakefile'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2017:in `block in load_rakefile'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2016:in `load_rakefile'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2000:in `block in run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/lib/rake.rb:1998:in `run'
C:/Ruby193/lib/ruby/gems/1.9.1/gems/rake-0.8.7/bin/rake:31:in `<top (required)>'
C:/Ruby193/bin/rake:23:in `load'
C:/Ruby193/bin/rake:23:in `<main>'

**Comment by Raj9039852537** [comment]
finaly server started.
sqlite3 is included in path
now following errors 
Jammit Warning: No asset match 'public/stylesheet/editor.css'
game.css
editor.js
game.js

**Comment by Raj9039852537** [comment]
build again with python &
now everything is working

**Comment by Raj9039852537** [comment]
sir
thank you very much for your kind support
