### ISSUE TITLE
Redo server code to reset bit-rot

### ISSUE THREAD

**Issue by evanw** [evanw/rapt#12]
The server currently needs ruby <2.0 to avoid a [bug with respond_to?](http://dev.af83.com/2013/10/21/ruby-2-0-respond-to.html). I have no idea what version of ruby we were using, but OS X no longer ships with gcc so ruby versions older than 1.9.3-p125 refuse to build. The llvm-gcc command can be used to build 1.9.3-p125 but we should probably update the code to use modern versions of stuff. Other things have probably bit-rotted as well.

**Comment by kayleg** [comment]
The server has been mostly upgraded to Rails 4.2 which fixes the ruby issues. 
Checkout the rails4 branch

The levels are not grouping on my local copy - didn't look into it.

We still need to upgrade jquery, remove Prototype and scriptaculous and probably some other js libraries

**Comment by evanw** [comment]
Awesome! Thanks @kayleg, this is great. I just checked out the rails4 branch and started to get more stuff working. It looks like our old code wasn't meant to be all combined together, so I removed the manifest stuff. I was able to get the game running fine and the editor running up until saving, where I'm getting a 401 error. I'll try to look at this more over the weekend.

**Comment by justin-ardini** [comment]
Thanks guys. Let me know if I can help, I'll have some free time on Saturday.

**Comment by kayleg** [comment]
@evanw I got the editor to save. It was missing the CSRF tokens from the ajax requests.

**Comment by evanw** [comment]
This is now fixed. The site is up again and rails4 is now in master. Thanks to @kayleg for all of his help!
