### ISSUE TITLE
Move off the Bamboo stack on Heroku

### ISSUE THREAD

**Issue by evanw** [evanw/rapt#13]
Heroku will turn off support for its Bamboo stack on March 16th, 2015, after which our site will no longer work. They want us to migrate to our stuff to their Cedar stack. Other options include not using Heroku.

**Comment by justin-ardini** [comment]
This also involves moving off of sqlite3.  From https://devcenter.heroku.com/articles/sqlite3:

> Heroku’s Cedar stack has an ephemeral filesystem. You can write to it, and you can read from it, but
> the contents will be cleared periodically. If you were to use SQLite on Heroku, you would lose your
> entire database at least once every 24 hours.

**Comment by kayleg** [comment]
We are only using sqlite3 in development - on heroku it switches to postresql
